### PR TITLE
Document compatibility with java 21 additionally to java 17

### PR DESCRIPTION
**Pull request by alexnb**
[Trello card](https://trello.com/c/IyPXeyWv/2213-officially-support-java-21)

Depends on [NOM backend PR 1604](https://github.com/neo-technology/neo4j-ops-manager-backend/pull/1604)

----

If you open a PR that needs to go into a current version, you need to *cherry-pick your commit from dev over to the current version branch*. Only then will the proper builds that generate html/pdf be run. But beware: Docs will be generated but not published automatically!

- [x] N/A - or - I have added the appropriate "cherry-pick-to" labels to this PR so I don't forget to do this later!

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-ops-manager-218.surge.sh

Updated pages:
- [Linux first look guide](https://neo4j-docs-ops-manager-218.surge.sh/ops-manager/1.10/first-look/linux-first-look)
- [Server installation](https://neo4j-docs-ops-manager-218.surge.sh/ops-manager/1.10/installation/server)
- [Architecture](https://neo4j-docs-ops-manager-218.surge.sh/ops-manager/1.10/introduction/architecture)
- [Types of deployment](https://neo4j-docs-ops-manager-218.surge.sh/ops-manager/1.10/introduction/deployment)

**Review by ravikiran-sulikeri — APPROVED** [review]
LGTM 👍

**Review by AlexicaWright — APPROVED** [review]
LGTM!

**Review by AlexicaWright — APPROVED** [review]
LGTM!

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Pull request merged**
